#!/bin/bash
DIR=$(realpath $(dirname $0))
if [ "$PYTHONPATH" == "" ]; then
	export PYTHONPATH=$DIR
else
	export PYTHONPATH=$PYTHONPATH:$DIR
fi

cd $DIR/src
python3 main.py >  ../log/cyberbox.log 2>&1
